"""initial

Revision ID: 0aa7ad5aec23
Revises: 
Create Date: 2026-06-02 16:01:52.055637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0aa7ad5aec23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
