"""add triggers and trigger_activations

Revision ID: 9ef52e9f49bd
Revises: 0aa7ad5aec23
Create Date: 2026-06-02 16:33:47.284453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ef52e9f49bd'
down_revision: Union[str, None] = '0aa7ad5aec23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hazard_type', sa.String(length=64), nullable=False),
    sa.Column('variable', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_id'), 'triggers', ['id'], unique=False)
    op.create_table('trigger_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_activations_forecast_id'), 'trigger_activations', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_trigger_activations_id'), 'trigger_activations', ['id'], unique=False)
    op.create_index(op.f('ix_trigger_activations_trigger_id'), 'trigger_activations', ['trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_activations_trigger_id'), table_name='trigger_activations')
    op.drop_index(op.f('ix_trigger_activations_id'), table_name='trigger_activations')
    op.drop_index(op.f('ix_trigger_activations_forecast_id'), table_name='trigger_activations')
    op.drop_table('trigger_activations')
    op.drop_index(op.f('ix_triggers_id'), table_name='triggers')
    op.drop_table('triggers')
    # ### end Alembic commands ###
